---

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\Program Files\Git\cmd;C:/Windows/system32

  - echo %PATH%

  - ruby --version
  - where ruby

  - gem --version
  - where gem

  - gem install bundler --version 1.17.1 --force
  - bundle --version

build_script:
  - bundle config force_ruby_platform true
  - bundle install --jobs 3 --retry 3 --path .bundle

test_script:
  - bundle exec ruby -rrouge

environment:
  matrix:
    - ruby_version: 25
