---

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\Program Files\Git\cmd;C:/Windows/system32

  - echo %PATH%

  - ruby --version
  - where ruby

  - gem --version
  - where gem

  - git clone https://github.com/bundler/bundler
  - cd bundler
  - git checkout segiddins/gemspec-force-ruby-platform
  - cd ..
  - ruby bundler/bin/bundle --version

build_script:
  - ruby bundler/bin/bundle config force_ruby_platform true
  - ruby bundler/bin/bundle install --jobs 3 --retry 3

test_script:
  - ruby bundler/bin/bundle config
  - ruby -Ibundler/lib -rbundler/setup -rrouge -e "puts 'OK'"

environment:
  matrix:
    - ruby_version: 25
